packages:
  - "."

minimumReleaseAge: 1440

allowBuilds:
  '@nestjs/core': true
  '@scarf/scarf': false
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@pkgr/core@0.3.6'
  - eslint-plugin-prettier@5.5.6
  - synckit@0.11.13

auditConfig:
  ignoreCves: []
