# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "10.20.0"

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24.10.0"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: (Test:) static
        run: pnpm run test:static

      - name: (Test:) Unit
        timeout-minutes: 15
        run: pnpm run test:unit

      - name: (Test:) e2e
        timeout-minutes: 15
        run: pnpm run test:e2e

      - name: (Build:) Docs
        run: pnpm run build:api-docs

      - name: (Build:) Project
        run: pnpm run build:app
